### ISSUE TITLE
Perk editing

### ISSUE THREAD

**Issue by start-5** [start-5/TiTS.JS-Save-Editor#12]
Perk editing

**Comment by sprunkwallace** [comment]
still missing a few perks, but im mainly looking for treated readiness

**Comment by sprunkwallace** [comment]
inhuman desire perk is broken now, behaving similarly to when editing dong size would have the decimal in the wrong place. i want inhuman desire set to 200, not 1,000,200

**Comment by start-5** [comment]
> inhuman desire perk is broken now, behaving similarly to when editing dong size would have the decimal in the wrong place. i want inhuman desire set to 200, not 1,000,200

Oh you’re right, I didn’t see that, thanks
