### ISSUE TITLE
Body array editing

### ISSUE THREAD

**Issue by start-5** [start-5/TiTS.JS-Save-Editor#16]
edit arrays that contain nested arrays/objects

**Comment by sprunkwallace** [comment]
not sure if it goes here, but will you be adding multi character editing? so we can edit npc capacities and the like?

**Comment by start-5** [comment]
> not sure if it goes here, but will you be adding multi character editing? so we can edit npc capacities and the like?

Yes, actually, this is already implemented and working for most stuff that’s visible

**Comment by sprunkwallace** [comment]
> > not sure if it goes here, but will you be adding multi character editing? so we can edit npc capacities and the like?
> 
> Yes, actually, this is already implemented and working for most stuff that’s visible

oh shit, u rite, my bad. didn't notice. thanks.

**Comment by sprunkwallace** [comment]
yo, new problem with cock editing. editing the flare also adds the goo leg for penises. in fact, there are multiple issues with penis flags, including having flags that shouldnt be accessible for penises
