### ISSUE TITLE
Perks missing and single sorted

### ISSUE THREAD

**Issue by LordGraveless** [start-5/TiTS.JS-Save-Editor#23]
Editor is missing multiple perks out of roughly 205 total and are sorted alphabetically only rather then perk type (Creation/Class/Event/Treatment/Item/General/NPC/Ship) _then_ alphabetically

**Comment by start-5** [comment]
As of the latest push, perks are up to date.

> (Creation/Class/Event/Treatment/Item/General/NPC/Ship) then alphabetically

This is near impossible to accomplish unless it's done manually, which I'm not going to do
