### ISSUE TITLE
Enabling Ship Installation Flags don't work properly

### ISSUE THREAD

**Issue by devlman127** [start-5/TiTS.JS-Save-Editor#24]
Enabling the installation flags early on in my game, but other than the Dong Designer (which I have already) and the Orgasmender they don't appear in the instillation area. One strange outlier is the Buttslutinator, which is labeled correctly in the installation screen but upon interacting reveals itself to be an Orgasmender.

**Comment by start-5** [comment]
I tested with all installables and this seems to be working correctly as of the deployed version. It might have been an issue back when the editor was outdated and breaking when loading files. Please reopen if you can still reproduce the issue
