### ISSUE TITLE
Can't edit any variables after loading file

### ISSUE THREAD

**Issue by Yahp1** [start-5/TiTS.JS-Save-Editor#27]
An internal error ocurred while processing the save data

Error: Unable to process binding "numberInput: function(){return selectedCharacter().obj.ballFullness }"
Message: Pass a function that returns the value of the ko.computed

Can provide save file if needed

**Comment by sprunkwallace** [comment]
> An internal error ocurred while processing the save data
> 
> Error: Unable to process binding "numberInput: function(){return selectedCharacter().obj.ballFullness }" Message: Pass a function that returns the value of the ko.computed
> 
> Can provide save file if needed

pretty sure start 5 is dead. gonna have to wait for someone else to do a save editor

**Comment by sprunkwallace** [comment]
> An internal error ocurred while processing the save data
> 
> Error: Unable to process binding "numberInput: function(){return selectedCharacter().obj.ballFullness }" Message: Pass a function that returns the value of the ko.computed
> 
> Can provide save file if needed

you could also try the save editor on a different browser, chrome based browsers are a bit fucky rn

**Comment by sprunkwallace** [comment]
> I have reactivated the project and will (eventually) add/fix all features that I had intended initially.

HOLY SHIT you're alive. i legit thought you got into a car accident or something, with how you dropped off the face of the earth
