### ISSUE TITLE
next items to focus on if still working on this

### ISSUE THREAD

**Issue by DasherOfZombies** [start-5/TiTS.JS-Save-Editor#34]
hello I would like it if you added tauric legs and finished up all them, and I would also like it if you worked on at least allowing us to add Gentelia, if You don't want to work on it then some time can you show me how? I can send you the progress stuff, I don't care about credit, since it would still go to you for teaching me how to add to your little program here XD

**Comment by start-5** [comment]
I have reactivated the project and will (eventually) add/fix all features that I had intended initially, which includes your request.
