### ISSUE TITLE
Failed to load data

### ISSUE THREAD

**Issue by MrNobody332** [start-5/TiTS.JS-Save-Editor#59]
ReferenceError: Unable to process binding "numberinput: function() {return fullness}" Message: fullness is not found.

I get this error when trying to load my original file after update. Now if I transfer areas I get this "Without any flowers located on your body, you feel the need to produce spores fade. While this relaxes your body’s sexual urges, you know that producing any new flowers will have you ready for pollination again. "  So the problem is the flower tail cunt did not get transferred with the new data conversion or it was removed from game. 

However After this I can save and load that data on the editor, but I see no way to get my flow tail cunt back. is there any way I can fix this?

**Comment by MrNobody332** [comment]
its an error caused by the old data conversion. tail cunts get messed up and removed thats why I couldnt load the file until after moving and it being registered as missing then resaving.

**Comment by start-5** [comment]
Oh, gotcha. Unfortunately, there's not much I or the editor can do about the conversion shenanigans. Tail editing is in the queue of stuff to be implemented, though, so you'll be able to mess with it soon, stay tuned.

**Comment by start-5** [comment]
If you're still looking for this, the newest update (#60) added some features that might help
