### ISSUE TITLE
Perks do not add/remove correctly

### ISSUE THREAD

**Issue by BasilMuse** [start-5/TiTS.JS-Save-Editor#64]
Save editor doesn't properly catch all perks that are on the character when loading the file, and allows you to add perks that already exist on the character. This leads to funny issues of having double the same perk, but it also means you can't remove the original. 
![image](https://user-images.githubusercontent.com/127893874/225121391-d820213a-87d5-43d7-a5f7-2859a2cb0abe.png)
![image](https://user-images.githubusercontent.com/127893874/225121467-27cf4348-5ba3-4756-84bb-a67b6c50f6fc.png)

**Comment by BasilMuse** [comment]
![image](https://user-images.githubusercontent.com/127893874/225121878-0f42b27b-bd02-4054-9a5f-9db93a55cc6a.png)
![image](https://user-images.githubusercontent.com/127893874/225121936-a18d42ab-48c9-4fc2-b172-6402c944d8e3.png)
Just another picture example

**Comment by start-5** [comment]
Strange. Please post the save file that this happened with and I'll take a look

**Comment by BasilMuse** [comment]
[Mauve (H) - 14Hrs 49Mins, 29 Days - Casstech Z14, Kalas (2).zip](https://github.com/start-5/TiTS.JS-Save-Editor/files/10980622/Mauve.H.-.14Hrs.49Mins.29.Days.-.Casstech.Z14.Kalas.2.zip)

**Comment by start-5** [comment]
So far I've tried all I can think of to replicate the issue but no luck.

Some context: The editor will first prioritize perks already owned by the character, and only then add whatever else is not owned to the selectable pool. This is to avoid this exact problem and as far as I've seen and re-tested it's doing its job.

I've also seen that this only happened to perks and not status effects, even though they both use the same system described above.

Is this the save after editing it for the first time? If not, can you also post that one and any others in between?

>but it also means you can't remove the original. 

As a workaround you can remove the dupes by unselecting one of the dupes and saving it like that. If you want to see it visually gone: unselecting the dupe, switching characters and then switching back to PC should remove the dupe from the list.
