### ISSUE TITLE
quest canceled after stat editing

### ISSUE THREAD

**Issue by polargeorge** [start-5/TiTS.JS-Save-Editor#76]
edited my stats to 60 and after loading back, the progress in current quest is gone and unable to restart. currently in dhaal, cannot attend party, feruze not in bar and feruze not at taxi. received email about the lead.

**Comment by polargeorge** [comment]
> Yes, this is caused by the editor failing to clear its state when there is a file already loaded and you load another one on top of it. See #74 for more details. Working on a fix now.
> 
> In the meantime, reloading the editor page after saving the edited file should not cause the issue.

thank you for the reply, ill try that now

**Comment by start-5** [comment]
Found some time to work on this, loading saves on top of each other should work now
