### ISSUE TITLE
editor not opening.

### ISSUE THREAD

**Issue by meero619** [start-5/TiTS.JS-Save-Editor#84]
Hello there, pressing on the link to open the editor gives me this error.
An unhandled exception ocurred! If you can, please open a GitHub issue so it can be fixed. Select "OK" to copy the error to your clipboard:

Message: $ is not defined
Stacktrace: @https://start-5.github.io/TiTS.JS-Save-Editor/:150:9

**Comment by mfrw-mf** [comment]
Message: $ is not defined
Stacktrace: ReferenceError: $ is not defined
    at https://start-5.github.io/TiTS.JS-Save-Editor/:150:9

**Comment by start-5** [comment]
This is an issue with a core script that is not being loaded correctly.

Works for me, though I need to test more browsers to be sure.

- What browser and browser version are you using?
- Has the editor worked before? Have you been able to open it before and this error just now started popping up?

**Comment by meero619** [comment]
well, I'm using firefox.
It works now just fine though, no idea what was wrong.

**Comment by start-5** [comment]
If I had to guess, the site that hosts the script might have been down intermittently. 

I’ll make it so it uses local scripts to avoid this in the future, not sure why I made it use remote instead of local scripts in the first place

**Comment by meero619** [comment]
thank you so much for your hard work. would it be possible to edit ship stats in the future? :)

**Comment by start-5** [comment]
I’d have to see how ships work. If it’s not prone to breaking saves it can probably be added. No promises though.

**Comment by mfrw-mf** [comment]
i am using chrome and it was working when one day it stopped

**Comment by start-5** [comment]
Please try a different browser. If that doesn’t work, there’s something on your device that’s blocking the script, it could be an ad/content blocker or some firewall on your system.

Opening the browser’s dev console (F12 or ctrl+shift+i) may spit out more information about why it’s not loading.

I’ll push an update to use local scripts whenever I have time

**Comment by mfrw-mf** [comment]
i have 3 browser not even one is opening it and this is what it say on f12(Failed to load resource: net::ERR_CONNECTION_RESET
jquery.min.js:1     Failed to load resource: net::ERR_CONNECTION_RESET
popper.min.js:1     Failed to load resource: net::ERR_CONNECTION_RESET
bootstrap.bundle.min.js:1     Failed to load resource: net::ERR_CONNECTION_RESET
typeahead.js:37 Uncaught TypeError: Cannot read properties of undefined (reading 'isArray')
    at typeahead.js:37:24
    at typeahead.js:161:6
    at typeahead.js:16:9
    at typeahead.js:18:3
(index):150 Uncaught ReferenceError: $ is not defined
    at (index):150:9)

**Comment by start-5** [comment]
Yup, it's an issue on your end regarding your network, no idea exactly what it is.

**Comment by start-5** [comment]
>i have 3 browser not even one is opening it and this is what it say on f12(Failed to load resource: net::ERR_CONNECTION_RESET
jquery.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET

Let me know if the latest update fixes the issue

**Comment by mfrw-mf** [comment]
> > i have 3 browser not even one is opening it and this is what it say on f12(Failed to load resource: net::ERR_CONNECTION_RESET
> > jquery.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
> 
> Let me know if the latest update fixes the issue

thanks for your hard work it is working now
