### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by mfrw-mf** [start-5/TiTS.JS-Save-Editor#85]
it give me this (
Message: $ is not defined
Stacktrace: ReferenceError: $ is not defined
at https://start-5.github.io/TiTS.JS-Save-Editor/:150:9)

**Comment by mfrw-mf** [comment]
Message: $ is not defined
Stacktrace: ReferenceError: $ is not defined
    at https://start-5.github.io/TiTS.JS-Save-Editor/:150:9

**Comment by start-5** [comment]
Duplicate of #84

**Comment by mfrw-mf** [comment]
so how do i fix it

**Comment by mfrw-mf** [comment]
it is still not working
